### ISSUE TITLE
Is there a way to listen for global keypresses?

### ISSUE THREAD

**Issue by seagreen** [pkamenarsky/concur-replica#6]
I'd like to do this for my little game. There are workarounds like requiring the user to select an element and then listen for keypresses on that element, but I'd obviously like to avoid that.

Thanks!

**Comment by pkamenarsky** [comment]
Not at the moment, but it's interesting to think about how this might be implemented. My first thought is to go with something like this:

```
example = document [ onClick ... ] [ div [] [ ... ] ]
```

Of course, this would require to special-casing the `document` `Widget`, since it's not an ordinary DOM element (i.e. it's only valid at the root and can't be created or destroyed), but that might be a reasonable trafeoff.

Any other ideas?

**Comment by seagreen** [comment]
Another solution that might be worth investigating is a generic way to communicate with JS running on the page. I'm imagining something like Elm's [ports mechanism](https://guide.elm-lang.org/interop/ports.html).

That would give the user a way to solve this problem (by writing JS that listens for `onkeydown` and `onkeyup` events and sends them to the server) and would also be useful in other situations.

Is that something you've thought about?

**Comment by pkamenarsky** [comment]
I think this should be possible now using the new JS FFI (see #7).

**Comment by seagreen** [comment]
Agreed, I think we can close this.
